services:
  # 1. Il Backend Go
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app # Montiamo il codice locale dentro il container
    environment:
      - APP_ENV=dev
      - FRONTEND_URL=http://frontend:5173
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=gotype
      - DB_PORT=5432
      - JWT_SECRET=dev_secret_key
    depends_on:
      - postgres
      - frontend

  # 2. Il Frontend React/Vite
  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NPM_CONFIG_UPDATE_NOTIFIER=false
    command: sh -c "npm install && npm run dev -- --host"
    stdin_open: true
    tty: true

  # 3. Database Postgres
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gotype
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
